openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://travel-api.test'
paths:
  /api/v1/user:
    get:
      summary: ''
      operationId: getApiV1User
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/travels:
    get:
      summary: ''
      operationId: getApiV1Travels
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 9c91b52d-1f96-431c-b7e6-a8cead2728c7
                      name: 'My 4 new travel'
                      slug: my-4-new-travel
                      description: 'The third best jor ever!'
                      number_of_days: 3
                      number_of_nights: 2
                    -
                      id: 9c91bf59-ecae-4aca-993a-e0efc09d3742
                      name: 'My2new travel'
                      slug: my2new-travela
                      description: 'The 2 best jor ever!'
                      number_of_days: 2
                      number_of_nights: 1
                  links:
                    first: 'http://travel-api.test/api/v1/travels?page=1'
                    last: 'http://travel-api.test/api/v1/travels?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://travel-api.test/api/v1/travels?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://travel-api.test/api/v1/travels'
                    per_page: 15
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 9c91b52d-1f96-431c-b7e6-a8cead2728c7
                        name: 'My 4 new travel'
                        slug: my-4-new-travel
                        description: 'The third best jor ever!'
                        number_of_days: 3
                        number_of_nights: 2
                      -
                        id: 9c91bf59-ecae-4aca-993a-e0efc09d3742
                        name: 'My2new travel'
                        slug: my2new-travela
                        description: 'The 2 best jor ever!'
                        number_of_days: 2
                        number_of_nights: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 9c91b52d-1f96-431c-b7e6-a8cead2728c7
                        name:
                          type: string
                          example: 'My 4 new travel'
                        slug:
                          type: string
                          example: my-4-new-travel
                        description:
                          type: string
                          example: 'The third best jor ever!'
                        number_of_days:
                          type: integer
                          example: 3
                        number_of_nights:
                          type: integer
                          example: 2
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://travel-api.test/api/v1/travels?page=1'
                      last:
                        type: string
                        example: 'http://travel-api.test/api/v1/travels?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://travel-api.test/api/v1/travels?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://travel-api.test/api/v1/travels'
                      per_page:
                        type: integer
                        example: 15
                      to:
                        type: integer
                        example: 2
                      total:
                        type: integer
                        example: 2
      tags:
        - Endpoints
      security: []
  '/api/v1/travels/{travel_slug}/tours':
    get:
      summary: ''
      operationId: getApiV1TravelsTravel_slugTours
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Travel] 9c8de349-f561-4d02-baf8-e9e969f2e0a8'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Travel] 9c8de349-f561-4d02-baf8-e9e969f2e0a8'
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                priceFrom:
                  type: number
                  description: ''
                  example: 3335.83549
                priceTo:
                  type: number
                  description: ''
                  example: 835717.88780512
                dateFrom:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-07-23T17:14:56'
                dateTo:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-07-23T17:14:56'
                sortBy:
                  type: string
                  description: ''
                  example: price
                  enum:
                    - price
                sortOrder:
                  type: string
                  description: ''
                  example: asc
                  enum:
                    - asc
                    - desc
      security: []
    parameters:
      -
        in: path
        name: travel_slug
        description: 'The slug of the travel.'
        example: 9c8de349-f561-4d02-baf8-e9e969f2e0a8
        required: true
        schema:
          type: string
  /api/v1/admin/travels:
    post:
      summary: ''
      operationId: postApiV1AdminTravels
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_public:
                  type: boolean
                  description: ''
                  example: false
                name:
                  type: string
                  description: ''
                  example: similique
                description:
                  type: string
                  description: ''
                  example: impedit
                number_of_days:
                  type: integer
                  description: ''
                  example: 11
              required:
                - name
                - description
                - number_of_days
      security: []
  '/api/v1/admin/travels/{travel_id}/tours':
    post:
      summary: ''
      operationId: postApiV1AdminTravelsTravel_idTours
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: alias
                starting_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-07-23T17:14:56'
                ending_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after <code>starting_date</code>.'
                  example: '2061-04-11'
                price:
                  type: number
                  description: ''
                  example: 5627074.5657022
              required:
                - name
                - starting_date
                - ending_date
                - price
      security: []
    parameters:
      -
        in: path
        name: travel_id
        description: 'The ID of the travel.'
        example: 9c8de349-f561-4d02-baf8-e9e969f2e0a8
        required: true
        schema:
          type: string
  '/api/v1/admin/travels/{travel_id}':
    put:
      summary: ''
      operationId: putApiV1AdminTravelsTravel_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_public:
                  type: boolean
                  description: ''
                  example: true
                name:
                  type: string
                  description: ''
                  example: consectetur
                description:
                  type: string
                  description: ''
                  example: qui
                number_of_days:
                  type: integer
                  description: ''
                  example: 4
              required:
                - name
                - description
                - number_of_days
      security: []
    parameters:
      -
        in: path
        name: travel_id
        description: 'The ID of the travel.'
        example: 9c8de349-f561-4d02-baf8-e9e969f2e0a8
        required: true
        schema:
          type: string
  /api/v1/login:
    post:
      summary: 'Handle the incoming request.'
      operationId: handleTheIncomingRequest
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: brooke.vonrueden@example.com
                password:
                  type: string
                  description: ''
                  example: aspernatur
              required:
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
